# Poetry workflow 
name: Python poetry application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.9"
          cache: "poetry"
      - run: poetry install

      - name: Lint with pylint
        run: |
          poetry run pylint src --fail-under=10

      - name: Lint with pylint tests
        run: |
          poetry run pylint test --fail-under=10

      - name: Mypy checking
        run: |
          poetry run mypy src --install-types

      - name: Mypy checking tests
        run: |
          poetry run mypy test --install-types

      - name: Test with pytest
        run: |
          poetry run pytest test
